name: Test
on: [push]
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: tre
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: node --version
